#data-split configuration
data_split:
  target_column: loan_paid_back

  test_size_1: 0.3 #70:30 train test split
  test_size_2: 0.5 #50:50 split between 30% of test set as test and validation

  stratify: true
  random_state: 11

pytorch:
  batch_size: 32
  epoch: 10
  learning_rate: 0.0001
  weight_decay: 0.00001
  model_input_dim: 11


